"""Initial enterprise schema

Revision ID: 76563679f5d2
Revises: 
Create Date: 2026-02-20 23:50:39.597787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76563679f5d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=512), nullable=True),
    sa.Column('expected_cost', sa.Float(), nullable=False),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('deviation_percent', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_organization_id'), 'anomalies', ['organization_id'], unique=False)
    op.create_table('cloud_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('credentials_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_accounts_organization_id'), 'cloud_accounts', ['organization_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('forecast_date', sa.DateTime(), nullable=False),
    sa.Column('predicted_cost', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_organization_id'), 'forecasts', ['organization_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=512), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('potential_savings', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_organization_id'), 'recommendations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recommendations_resource_id'), 'recommendations', ['resource_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cost_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('cloud_account_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=512), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('usage_quantity', sa.Float(), nullable=True),
    sa.Column('usage_unit', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_snapshots_cloud_account_id'), 'cost_snapshots', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_organization_id'), 'cost_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_resource_id'), 'cost_snapshots', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_service'), 'cost_snapshots', ['service'], unique=False)
    op.create_index(op.f('ix_cost_snapshots_timestamp'), 'cost_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_snapshots_timestamp'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_service'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_resource_id'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_organization_id'), table_name='cost_snapshots')
    op.drop_index(op.f('ix_cost_snapshots_cloud_account_id'), table_name='cost_snapshots')
    op.drop_table('cost_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_recommendations_resource_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_organization_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_forecasts_organization_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_date'), table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_cloud_accounts_organization_id'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_anomalies_organization_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('organizations')
    # ### end Alembic commands ###
